### ISSUE TITLE
Roadmap to release

### ISSUE THREAD

**Issue by catmando** [ruby-hyperloop/hyper-react#1]
_From @zetachang on February 18, 2015 14:4_
- [x] Add test for state should be original object
- [x] props should remain the same
- [x] ~~set_state callback spec~~ actually hard to write. 
- [ ] Compatible of DSL with original one
- [ ] Add test for todos
- [x] ~~initial state rely on props?~~ [considered as an anti-pattern](http://facebook.github.io/react/tips/props-in-getInitialState-as-anti-pattern.html)
- [ ] select should allow array (http://facebook.github.io/react/tips/props-in-getInitialState-as-anti-pattern.html)
- [x] Class name
- [x] Mixins
- [x] alias_native event key code.... etc
- [x] Upgrade to opal 0.7.0
- [x] Write README...
- [ ] Coverage of APIs, refer to #2

_Copied from original issue: zetachang/react.rb#1_

**Comment by catmando** [comment]
_From @ajjahn on October 30, 2015 14:34_

@catmando Same for this one...

> Of the unchecked items in this list, do you know if any have been implemented?
